"""Cambiar detalle a Text

Revision ID: b3c8fc310e06
Revises: 6896e4dfe79e
Create Date: 2025-06-23 13:53:10.354268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c8fc310e06'
down_revision = '6896e4dfe79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
