"""crear tabla visitas_unicas

Revision ID: e056b6a75721
Revises: 203a4663e372
Create Date: 2025-06-20 13:22:08.886466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e056b6a75721'
down_revision = '203a4663e372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas_unicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas_unicas')
    # ### end Alembic commands ###
